# 虚拟环境 https://help.github.com/cn/articles/virtual-environments-for-github-actions
name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Pack and push
        uses: actions/setup-nuget@v1
        run: |
          nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/xxred/index.json" -UserName xxred -Password ${{ secrets.GITHUB_TOKEN }}
          dotnet pack "Easy.Admin/Easy.Admin.csproj" -c Release -o pack
          nuget push "Easy.Admin.nupkg" -Source "GitHub"
