# 虚拟环境 https://help.github.com/cn/articles/virtual-environments-for-github-actions
# action市场 https://github.com/marketplace?type=actions
# 自定义action https://help.github.com/cn/articles/metadata-syntax-for-github-actions
# action例子 https://github.com/actions
# github-nuget https://help.github.com/en/articles/configuring-nuget-for-use-with-github-package-registry
name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Setup Nuget
        run: |
          if [ ! -d  ~/.nuget ]; then mkdir ~/.nuget; fi
          cd ~/.nuget
          pwd
          wget -O tar https://github.com/microsoft/artifacts-credprovider/releases/download/0.1.18/Microsoft.NuGet.CredentialProvider.tar.gz
          tar -xf tar
          echo "${{ secrets.GITHUB_TOKEN }}"
          export VSS_NUGET_EXTERNAL_FEED_ENDPOINTS='{  "endpointCredentials": [    {      "endpoint": "https://nuget.pkg.github.com/xxred/index.json",      "username": "xxred",      "password": "${{ secrets.nuget_token }}"    }  ]}'
      - name: Pack and push
        run: |
          ls ~/.nuget
          ls ~/.nuget/plugins
          dotnet pack "Easy.Admin/Easy.Admin.csproj" -c Release -o pack
          dotnet nuget push "Easy.Admin/pack/*.nupkg" -s "https://nuget.pkg.github.com/xxred/index.json"
