# 虚拟环境 https://help.github.com/cn/articles/virtual-environments-for-github-actions
# action市场 https://github.com/marketplace?type=actions
name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Pack and push
        run: |
          wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
          nuget.exe source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/xxred/index.json" -UserName xxred -Password ${{ secrets.GITHUB_TOKEN }}
          dotnet pack "Easy.Admin/Easy.Admin.csproj" -c Release -o pack
          nuget.exe push "Easy.Admin/pack/*.nupkg" -Source "GitHub"
